services:
  napcat:
    container_name: napcat
    environment:
      - tz=Asia/Shanghai
      - NAPCAT_UID=${NAPCAT_UID}
      - NAPCAT_GID=${NAPCAT_GID}
    ports:
      - 3000:3000
      - 3001:3001
      - 6099:6099
    restart: always
    volumes:
      - napcatQQ:/app/.config/QQ
      - napcatCONFIG:/app/napcat/config
    image: mlikiowa/napcat-docker:latest

  mongodb:
    container_name: mongodb
    environment:
      - tz=Asia/Shanghai
    expose:
      - "27017"
    restart: always
    volumes:
      - mongodb:/data/db
      - mongodbCONFIG:/data/configdb
    image: mongo:latest
    
  maimbot:
    container_name: maimbot
    build: .
    environment:
      - tz=Asia/Shanghai
    expose:
      - "8080:8080"
    restart: always
    depends_on:
      - mongodb
      - napcat
    volumes:
      - maimbotCONFIG:/app/config
    image: jiajiu/maimbot:latest
  

volumes:
  maimbotCONFIG:
  napcatQQ:
  napcatCONFIG:
  mongodb:
  mongodbCONFIG:
